RAW_FILE_NAME: 'Original_ObesityDataSet.csv' # the data used to train and validate the model
CURRENT_FILE_NAME: 'Current_ObesityDataSet.csv' # the new data used to monitor the model
TARGET_COLUMN: 'NObeyesdad'
DATA_PATH: '/workspace/data/'
ARTIFACTS_PATH: '/workspace/models/artifacts/'
FEATURES_PATH: '/workspace/models/features/'
RESEARCH_ENVIRONMENT_PATH: '/workspace/notebooks/'
