apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000  # Exposed port inside the cluster
      targetPort: 8000
  type: ClusterIP  # Internal service
