apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80  # Expose Streamlit on port 80
      targetPort: 8501
  type: LoadBalancer  # External access
