name: Training Pipeline

on:
  push:
    paths:
      - 'src/model/**'
      - '.github/workflows/training-pipeline.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-training.txt

    - name: Run training script
      run: python src/model/train.py

    - name: Archive model
      run: |
        mkdir -p artifacts
        cp src/model/model.pkl artifacts/

    - name: Upload model artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-artifact
        path: artifacts/model.pkl

  package:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download model artifact
      uses: actions/download-artifact@v2
      with:
        name: model-artifact
        path: fastapi_app

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./fastapi_app
        push: true
        tags: ghcr.io/${{ github.repository }}/fastapi-app:latest